name: retrograph
channels:
  - rdkit
  - conda-forge
  - pytorch
  - anaconda
  - defaults
dependencies:
  - python=3.7
  - pandas
  - rdkit
  - tqdm
  - networkx
  - graphviz
  - python-graphviz
  - ruamel_yaml
  - cudatoolkit==11.3.1
  - pytorch==1.11.0
  - torchmetrics